# Generated by Django 3.1.4 on 2020-12-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddobaki', '0010_word_list2_word_list3_word_list4'),
    ]

    operations = [
        migrations.AddField(
            model_name='get_ddobaki',
            name='divided_label',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
